// <auto-generated />
using System;
using CrossPlatformDownloadManager.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrossPlatformDownloadManager.Data.Migrations
{
    [DbContext(typeof(DownloadManagerDbContext))]
    [Migration("20240826123126_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoAddLinkFromSites")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryHeaderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategorySaveDirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryHeaderId");

                    b.HasIndex("CategorySaveDirectoryId")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.CategoryFileExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryFileExtensions");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.CategoryHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoryHeaders");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.CategorySaveDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaveDirectory")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategorySaveDirectories");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.DownloadFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<float>("DownloadProgress")
                        .HasColumnType("REAL");

                    b.Property<int?>("DownloadQueueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTryDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QueuePriority")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Size")
                        .HasColumnType("REAL");

                    b.Property<byte?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("TimeLeft")
                        .HasColumnType("TEXT");

                    b.Property<float?>("TransferRate")
                        .HasColumnType("REAL");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DownloadQueueId");

                    b.ToTable("DownloadFiles");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.DownloadQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaysOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ExitProgramWhenDone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDaily")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("JustForDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RetryOnDownloadingFailed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ShowAlarmWhenDone")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("StartDownloadSchedule")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StartOnApplicationStartup")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("StopDownloadSchedule")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte?>("TurnOffComputerMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("TurnOffComputerWhenDone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DownloadQueues");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.Category", b =>
                {
                    b.HasOne("CrossPlatformDownloadManager.Data.Models.CategoryHeader", null)
                        .WithMany("Categories")
                        .HasForeignKey("CategoryHeaderId");

                    b.HasOne("CrossPlatformDownloadManager.Data.Models.CategorySaveDirectory", "CategorySaveDirectory")
                        .WithOne("Category")
                        .HasForeignKey("CrossPlatformDownloadManager.Data.Models.Category", "CategorySaveDirectoryId");

                    b.Navigation("CategorySaveDirectory");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.CategoryFileExtension", b =>
                {
                    b.HasOne("CrossPlatformDownloadManager.Data.Models.Category", "Category")
                        .WithMany("FileExtensions")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.DownloadFile", b =>
                {
                    b.HasOne("CrossPlatformDownloadManager.Data.Models.Category", "Category")
                        .WithMany("DownloadFiles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrossPlatformDownloadManager.Data.Models.DownloadQueue", "DownloadQueue")
                        .WithMany("DownloadFiles")
                        .HasForeignKey("DownloadQueueId");

                    b.Navigation("Category");

                    b.Navigation("DownloadQueue");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.Category", b =>
                {
                    b.Navigation("DownloadFiles");

                    b.Navigation("FileExtensions");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.CategoryHeader", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.CategorySaveDirectory", b =>
                {
                    b.Navigation("Category");
                });

            modelBuilder.Entity("CrossPlatformDownloadManager.Data.Models.DownloadQueue", b =>
                {
                    b.Navigation("DownloadFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
